### PR TITLE
Upgrade echarts to major version 5

### PR DESCRIPTION
**Pull request by mij**
Upgrades echarts from version 4.8.0 to 5.1.1.

- echarts 5 was released in late 2020
- its syntax breaks is a breaking change from the syntax of echarts 4
- users browsing the echarts gallery are exposed to version 5, which is confusing to newcomers

This PR:

- upgrades echarts
- updates uBlogger docs to reflect the new echarts syntax
- Adds a tip to import charts from echarts' interactive editor into uBlogger's shortcodes

### CODE REVIEW

**Comment by uPagge** [comment]
But thanks a lot for this update, I will try to study the changes in the week))

**Comment by uPagge** [comment]
Thanks a lot for your work. If you have a desire, could you please see why the diagram rendering does not work when launched locally?

**Comment by uPagge** [comment]
@mij Thanks a lot for your work. If you have a desire, could you please see why the diagram rendering does not work when launched locally?

**Comment by mij** [comment]
The `assets.html` partial simply does not output the HTML to load the echarts.js library while in the development environment. You're better poised to understand why that is (I'm not really experienced with Hugo templates), but here's the code which should be outputted and for whichever reason isn't:

https://github.com/uPagge/uBlogger/blob/d8e4e98885ef3f99b11f9fa28a8372d6cbafe736/layouts/partials/assets.html#L110

**Pull request merged**
